<?php

/**
 * BasesaFormsElement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $form_id
 * @property string $form_name
 * @property string $element_name
 * @property string $element_key
 * @property string $element_value
 * @property integer $element_type
 * @property integer $sort
 * 
 * @method integer        getFormId()        Returns the current record's "form_id" value
 * @method string         getFormName()      Returns the current record's "form_name" value
 * @method string         getElementName()   Returns the current record's "element_name" value
 * @method string         getElementKey()    Returns the current record's "element_key" value
 * @method string         getElementValue()  Returns the current record's "element_value" value
 * @method integer        getElementType()   Returns the current record's "element_type" value
 * @method integer        getSort()          Returns the current record's "sort" value
 * @method saFormsElement setFormId()        Sets the current record's "form_id" value
 * @method saFormsElement setFormName()      Sets the current record's "form_name" value
 * @method saFormsElement setElementName()   Sets the current record's "element_name" value
 * @method saFormsElement setElementKey()    Sets the current record's "element_key" value
 * @method saFormsElement setElementValue()  Sets the current record's "element_value" value
 * @method saFormsElement setElementType()   Sets the current record's "element_type" value
 * @method saFormsElement setSort()          Sets the current record's "sort" value
 * 
 * @package    authority
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesaFormsElement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sa_forms_element');
        $this->hasColumn('form_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('form_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('element_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('element_key', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('element_value', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('element_type', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('sort', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}