<?php

/**
 * BasesaForms
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $form_name
 * @property clob $form_content
 * @property clob $form_published
 * 
 * @method string  getFormName()       Returns the current record's "form_name" value
 * @method clob    getFormContent()    Returns the current record's "form_content" value
 * @method clob    getFormPublished()  Returns the current record's "form_published" value
 * @method saForms setFormName()       Sets the current record's "form_name" value
 * @method saForms setFormContent()    Sets the current record's "form_content" value
 * @method saForms setFormPublished()  Sets the current record's "form_published" value
 * 
 * @package    authority
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesaForms extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sa_forms');
        $this->hasColumn('form_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('form_content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('form_published', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}