<?php

/**
 * saFormsElementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class saFormsElementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object saFormsElementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('saFormsElement');
    }
}