<?php

/**
 * saFormsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class saFormsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object saFormsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('saForms');
    }
}