<?php

/**
 * saForms
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    authority
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class saForms extends BasesaForms
{
  function getFormUrl(){
  	$tmpFormId=$this->getId();  	 	
	$tmpFormUrl='/forms/show/id/'.$tmpFormId;
	$result=$tmpFormUrl;
  	return link_to('preview',$result);
  }
}