<?php

/**
 * saOrdersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class saOrdersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object saOrdersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('saOrders');
    }
}