<?php

/**
 * saOrdersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class saOrdersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object saOrdersTable
     */
    public static function getInstance()
    {

      $q = Doctrine_Core::getTable('saOrders')
        ->createQuery('c')
        ->orderBy('c.created_at ASC');
        return $q->execute(); 
    }
}
