generator:
  class: sfDoctrineGenerator
  param:
    model_class:           saOrders
    theme:                 project
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sa_orders
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [=id, form_name, created_at, updated_at]
        sort: [created_at, asc]
        object_actions: 
           View: { name: view, action: view, icon: backend/addcomment.png }		
           _delete: ~		   
      filter:  
        class: false
      form:    ~
      edit:    ~
      new:     ~
