<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }

    public function getNormalUserList(Doctrine_Query $query){
        $query = Doctrine_Query::create()->select(' * ')
              ->from('sfGuardUser u')
              ->where('u.is_super_admin = ?', '0')
              ->orderBy('created_at DESC');           
        return $query;            
    }    	
	
}